color0 #111416
color1 #ffb4ab
color2 #a0cbf1
color3 #b8c8d9
color4 #e2b9eb
color5 #a0cbf1
color6 #b8c8d9
color7 #e2e2e5
color8 #8c9198
color9 #ffb4ab
color10 #a0cbf1
color11 #b8c8d9
color12 #e2b9eb
color13 #a0cbf1
color14 #b8c8d9
color15 #e2e2e5

cursor                #e2e2e5
cursor_text_color     #111416
background            #111416
foreground            #e2e2e5
selection_foreground  #c2c7ce
selection_background  #42474d
active_border_color   #a0cbf1
inactive_border_color #42474d
url_color             #a0cbf1

active_tab_foreground   #003450
active_tab_background   #a0cbf1
inactive_tab_foreground #c2c7ce
inactive_tab_background #42474d
cursor_trail_color      #c2c7ce
